/**
 * Discovery Workflow Constants & Enums
 */
const DISCOVERY_CONSTANTS = Object.freeze({
  DEFAULT_PORT: 5001,
  
  REQUEST_STATUS: {
    PENDING: 'PENDING',
    PLANNING: 'PLANNING',
    DISCOVERING: 'DISCOVERING',
    CRAWLING: 'CRAWLING',
    ACQUIRED: 'ACQUIRED',
    FAILED: 'FAILED'
  },
  
  CRAWLER_TYPES: {
    HTTP: 'HTTP_CRAWLER',
    API: 'API_CRAWLER',
    BROWSER: 'BROWSER_CRAWLER'
  },
  
  OUTBOX_STATUS: {
    PENDING: 'PENDING',
    PUBLISHED: 'PUBLISHED',
    FAILED: 'FAILED'
  },

  AI_RETRY_LIMIT: 3,
  CRAWL_TIMEOUT_MS: 30000,
  DEFAULT_RANKING_SCORE: 0.8
});

module.exports = DISCOVERY_CONSTANTS;
